@startuml

entity CastMember {
    Id : Guid
    --
    CastMemberMovies : ICollection<CastMemberMovie>
    ' CastMemberKeyCodePlaceholder
    --
    Name1 : string
    ' CastMemberPropertyCodePlaceholder
}

' EntityCodePlaceholder

' RelationshipCodePlaceholder

@enduml
