@startuml

entity CastMember {
    Id : Guid
    --
    ' CastMemberKeyCodePlaceholder
    --
    ' CastMemberPropertyCodePlaceholder
}

' EntityCodePlaceholder

' RelationshipCodePlaceholder

@enduml
